// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Greeting$ReactTemplate = require("./Greeting.bs.js");
var HelloMsg$ReactTemplate = require("./HelloMsg.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, HelloMsg$ReactTemplate.make("Hello Reason React!", /* array */[])), "helloMsg");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Greeting$ReactTemplate.make("Hello, Good morning!", /* array */[])), "greet");

/*  Not a pure module */
